config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about", to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, :uniqueness => {:scope => :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    if @book_comment.save
      redirect_to book_path(@book)
    else
      @booker = @book.user
      @user = current_user
      render 'books/show'
    end

  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # def new
  #   @book = Book.new
  # end

  def index
    @books = Book.all
    @newbook = Book.new
    @user = current_user
  end

  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@newbook.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = current_user
    @booker = @book.user
    
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
      unless @book.user == current_user
        redirect_to books_path
      end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = book.favorites.new(user_id: current_user.id)
    favorite.save
    # if request.path == books_path
    #   redirect_to book_path(book)
    # else
    #   redirect_to books_path
    # end

    # redirect_back(fallback_location: root_path)
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
      unless @user == current_user
        redirect_to user_path(current_user.id)
      end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto">
      <h2>Editing Book</h2>
      
      <div class="text-danger">
        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <br>
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
      </div>

      
      <%= form_with model: @book, local: true do |f| %>
        <label for="title">Title</label><br>
        <%= f.text_field :title, autofocus: true %><br>
        <label for="body">Opinion</label><br>
        <%= f.text_area :body, autofocus: true %><br>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/books/index.html.erb
<div class="container">

  <p class="text-success"><%= flash[:notice] %></p>

  <div class="text-danger">
    <% if @newbook.errors.any? %>
      <h3><%= @newbook.errors.count %>errors prohibited this obj from being saved:</h3>
      <br>
      <% @newbook.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  </div>


  <div class="row">
    <div class="col-md-3 col-xs-3">

      <div class="user-info">
        <h1>User info</h1>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>

        <%= link_to edit_user_path(@user.id) do %>
          <div class="btn btn-outline-secondary btn-block">
            <span class="fas fa-user-cog"></span>
          </div>
        <% end %>

      </div>


      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model: @newbook, local: true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class: 'btn-success' %>
        <% end %>
      </div>

    </div>




    <div class="col-md-8 offset-md-1 col-xs-9">
      <div class="books">
        <h1>Bookers</h1>
        <table class="table table-hover">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :size => '45x45', fallback: "no_image.jpg" %>
                <% end %>
              </td>

              <td><%= link_to book.title, book_path(book.id) %></td>

              <td><%= book.body %></td>

            <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete, class: 'text-danger text-decoration-none' do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post, class: 'text-primary text-decoration-none' do %>
                  <i class="fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              </td>
            <% end %>

              <td>
                コメント数：<%= book.book_comments.count %>
              </td>

            </tr>
          <% end %>
        </table>

      </div>
    </div>

  </div>

</div>

app/views/books/show.html.erb
<div class="container">

  <p class="text-success"><%= flash[:notice] %></p>

  <div class="text-danger">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
      <br>
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  </div>

  <div class="text-danger">
    <% if @book_comment.errors.any? %>
      <%= @book_comment.errors.count %>errors prohibited this obj from being saved:
      <br>
      <% @book_comment.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  </div>


  <div class="row">
    <div class="col-md-3 col-xs-3">

      <div class="user-info">
        <h1>User info</h1>
        <%= attachment_image_tag @booker, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @booker.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @booker.introduction %></th>
          </tr>
        </table>

        <%= link_to edit_user_path(@booker.id) do %>
          <div class="btn btn-outline-secondary btn-block">
            <span class="fas fa-user-cog"></span>
          </div>
        <% end %>

      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model: @newbook, local: true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class: 'btn-success' %>
        <% end %>
      </div>

    </div>




    <div class="col-md-8 offset-md-1 col-xs-9">
      <div class="book-detail">
        <h1>Book detail</h1>
        <table class="table">
          <tr>
              <td><%= attachment_image_tag @booker, :profile_image, :size => '45x45', fallback: "no_image.jpg" %><br><%= link_to @booker.name, user_path(@booker.id) %></td>

              <td><%= link_to @book.title, book_path(@book.id) %></td>

              <td><%= @book.body %></td>

            <% if @book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(@book), method: :delete, class: 'text-danger text-decoration-none' do %>
                  <i class="fas fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(@book), method: :post, class: 'text-primary text-decoration-none' do %>
                  <i class="fas fa-heart"></i>
                  <%= @book.favorites.count %>
                <% end %>
              </td>
            <% end %>

              <td>
                コメント数：<%= @book.book_comments.count %>
              </td>

            <% if @booker.id == @user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-success' %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-danger' %></td>
            <% end %>
          </tr>
        </table>

        <div class="comments">
          <h4>Comment List</h4>
          <table class="table">
            <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td><%= attachment_image_tag book_comment.user, :profile_image, :size => '45x45', fallback: "no_image.jpg" %></td>
                <td><%= book_comment.user.name %></td>
                <td><%= book_comment.created_at.strftime('%Y/%m/%d') %></td>
                <td><%= book_comment.comment %></td>
                <% if book_comment.user == current_user %>
                  <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-danger' %></td>
                <% end %>
              </tr>
            <% end %>
          </table>
        </div>


        <div class="new-comment mb-4">
          <%= form_with(model: [@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, rows: '5', cols: '60' %>
            <%= f.submit "送信", class: 'ml-3 px-2' %>
          <% end %>
        </div>

      </div>
    </div>


  </div>

</div>

app/views/homes/about.html.erb
<div class="container">
  <div class='row'>
    <h1 class="mx-auto mt-5">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>© 2021　Ayumu Noda　All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
<div class="container">
  <p class="text-success"><%= flash[:notice] %></p>

  <div class="row">
    <div class="mx-auto mt-4">

      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>

      <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      </div>
      <div class="row">
        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
      </div>

    </div>
  </div>

</div>


<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>© 2021　Ayumu Noda　All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-secondary py-2">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/"><span class="text-light font-italic h4">Bookers</span></a>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto text-light">

            <% if user_signed_in? %>
              <li class="nav-item px-2">
                <%= link_to user_path(current_user.id), class: 'text-light text-decoration-none', method: :get do %>
                  <div class="home"><span class="fas fa-home mr-1"></span>Home</div>
                <% end %>
              </li>
              <li class="nav-item px-2">
                <%= link_to users_path, class: 'text-light text-decoration-none', method: :get do %>
                  <div class="users"><span class="fas fa-users mr-1"></span>Users</div>
                <% end %>
              </li>
              <li class="nav-item px-2">
                <%= link_to books_path, class: 'text-light text-decoration-none', method: :get do %>
                  <div class="books"><span class="fas fa-book-open mr-1"></span>Books</div>
                <% end %>
              </li>
              <li class="nav-item px-2">
                <%= link_to destroy_user_session_path, class: 'text-light text-decoration-none', method: :delete do %>
                  <div class="logout"><span class="fas fa-sign-out-alt mr-1"></span>logout</div>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item px-2">
                <%= link_to root_path, class: 'text-light text-decoration-none', method: :get do %>
                  <div class="home"><span class="fas fa-home mr-1"></span>Home</div>
                <% end %>
              </li>
              <li class="nav-item px-2">
                <%= link_to home_about_path, class: 'text-light text-decoration-none', method: :get do %>
                  <div class="about"><span class="fas fa-link mr-1"></span>About</div>
                <% end %>
              </li>
              <li class="nav-item px-2">
                <%= link_to new_user_registration_path, class: 'text-light text-decoration-none', method: :get do %>
                  <div class="sign-up"><span class="fas fa-user-plus mr-1"></span>sign up</div>
                <% end %>
              </li>
              <li class="nav-item px-2">
                <%= link_to new_user_session_path, class: 'text-light text-decoration-none', method: :get do %>
                  <div class="login"><span class="fas fa-sign-in-alt mr-1"></span>login</div>
                <% end %>
              </li>
            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto">
      <h2>User info</h2>

      <div class="text-danger">
        <% if @user.errors.any? %>a
          <%= @user.errors.count %>errors prohibited this obj from being saved:
          <br>
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
      </div>

      <%= form_with model: @user, local: true do |f| %>
        <label for="user-name">Name</label><br>
        <%= f.text_field :name, autofocus: true %><br>
        <label for="user-image">Image</label><br>
        <%= f.attachment_field :profile_image %><br>
        <label for="user-introduction">Introduction</label><br>
        <%= f.text_area :introduction, autofocus: true %><br>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">

  <p class="text-success"><%= flash[:notice] %></p>


  <div class="row">
    <div class="col-md-3 col-xs-3">

      <div class="user-info">
        <h1>User info</h1>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>

        <%= link_to edit_user_path(@user.id) do %>
          <div class="btn btn-outline-secondary btn-block">
            <span class="fas fa-user-cog"></span>
          </div>
        <% end %>

      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model: @book, local: true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class: 'btn-success' %>
        <% end %>
      </div>

    </div>




    <div class="col-md-8 offset-md-1 col-xs-9">
      <div class="users">
        <h1>Users</h1>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :size => '45x45', format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

  </div>

</div>

app/views/users/show.html.erb
<div class="container">

  <p class="text-success"><%= flash[:notice] %></p>


  <div class="row">
    <div class="col-md-3 col-xs-3">

      <div class="user-info">
        <h1>User info</h1>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>

        <% if @user == current_user %>
          <%= link_to edit_user_path(current_user.id) do %>
            <div class="btn btn-outline-secondary btn-block">
              <span class="fas fa-user-cog"></span>
            </div>
          <% end %>
        <% else %>
          <%= link_to edit_user_path(@user.id) do %>
            <div class="btn btn-outline-secondary btn-block">
              <span class="fas fa-user-cog"></span>
            </div>
          <% end %>
        <% end %>

      </div>

      <div class="new-book">
        <h1>New book</h1>
        <%= form_with model: @book, local: true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class: 'btn-success' %>
        <% end %>
      </div>

    </div>




    <div class="col-md-8 offset-md-1 col-xs-9">
      <div class="user">
        <h1>Books</h1>
        <table class="table table-hover">
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :size => '45x45', fallback: "no_image.jpg" %>
                <% end %>
              </td>

              <td><%= link_to book.title, book_path(book.id) %></td>

              <td><%= book.body %></td>

              <% if book.favorited_by?(current_user) %>
                <td>
                  <%= link_to book_favorites_path(book), method: :delete, class: 'text-danger text-decoration-none' do %>
                    <i class="fas fa-heart"></i>
                    <%= book.favorites.count %>
                  <% end %>
                </td>
              <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post, class: 'text-primary text-decoration-none' do %>
                    <i class="fas fa-heart"></i>
                    <%= book.favorites.count %>
                  <% end %>
                </td>
              <% end %>


              <td>コメント数：<%= book.book_comments.count %></td>

            </tr>
          <% end %>
        </table>
      </div>
    </div>

  </div>

</div>